Fix tiled BackgroundPainter performance
Juuxel/LibNinePatch pull request #2
Opened 2023-02-03 06:29 UTC by BlazingTwist

Wombo Combo Pull Request <link to be added>

I'm sorry this is such a massive change, but there was no fixing this without a sledgehammer.

The essence of the changes is to allow the GPU to handle tiling, rather than doing it on the CPU.

## Why I believe you should merge this:

I'll let the screenshot speak for itself.

Before:
![30 fps with the old tiling](https://user-images.githubusercontent.com/39350649/216528275-3b0b750a-7bd9-42b6-8fe6-47f388a12165.png)

After:
![374 fps with the new tiling](https://user-images.githubusercontent.com/39350649/216528350-2111b03e-3aed-4c4c-bb9f-929e258ddba5.png)

2023-02-03 16:07 UTC, Juuxel requested changes
Thanks for the PR! Some notes, and see my individual review comments as well.

- `TextureRegion` should be left intact along with the methods that use it.
- This change can be completely done without breaking changes and without removing functionality in the form of removing
  - texture regions
  - computing edge texture regions automatically based on a `cornerUv` builder method

2023-02-03 16:07 UTC, Juuxel commented on src/main/java/juuxel/libninepatch/NinePatch.java
> +         */
Existing code should not be reformatted.

2023-02-03 16:07 UTC, Juuxel commented on src/main/java/juuxel/libninepatch/NinePatch.java
> +                                         T bottomLeft, T bottomCenter, T bottomRight) {
The edge and corner textures should be optional additions in the builder.

2023-02-03 16:07 UTC, Juuxel commented on src/main/java/juuxel/libninepatch/NinePatch.java
> -        private float cornerV = 0f;
This functionality should remain as a fallback option for when texture regions for the sides and corners are not specified manually.

2023-02-03 16:07 UTC, Juuxel commented on src/main/java/juuxel/libninepatch/NinePatch.java
> +            this.textures = (T[][]) Array.newInstance(textureClass, 3, 3);
Separate fields for all of them would be better, no need to have an array.

2023-02-03 16:39 UTC, BlazingTwist commented
While I believe that the TextureRegion is a concept that should not be forced onto TextureRenderer implementations, I understand wanting to avoid breaking changes.

I'll have a look what I can do tomorrow-ish.

2023-02-03 19:20 UTC, Juuxel commented
TextureRegion is not really forced onto TextureRenderer implementations since the methods using it are `default` utility methods. The actual renderer only has to deal with its own `T` value combined with adjusted UV coordinates. (Unless they want to override the region methods too.)

2023-02-08 13:53 UTC, BlazingTwist commented
Alright, I did a re-design with preservation of TextureRegion in mind.

One crucial aspect here is eliminating all NinePatch specific UV coordinates before rendering occurs.
If TextureRenderer implementations wish to use modified UV coordinates they can just use an appropriate TextureType and corresponding textureAllocator.

(Once this PR reaches a merge-ready state in your eyes, I'll update the LibGUI PR)

2023-02-08 17:16 UTC, Juuxel requested changes
Looks a lot better, but still:

- I'm not planning to commit breaking changes. LNP is also part of LibGui's API, which would mean this change would be at earliest for MC 1.20 snapshots.
- `@NotNull` should not be used, it's considered the default unless there's `@Nullable`
- Type variables should not be upper camel case (`TextureType`) since they can be confused with actual types
- I believe removing the UV coordinates will not allow drawing partial side textures like this:
![diagram showing a tiled side that is partially cut off due to non-evenly divisible length](https://user-images.githubusercontent.com/6596629/217603524-1b642ad5-b945-49e3-a64a-e7b95c8d885e.png)

2023-02-09 01:20 UTC, BlazingTwist commented
> I'm not planning to commit breaking changes.

As I see it, there are two remaining options:
1. I can add a completely separate NinePatch class for tiling support, which can be opted into with the NinePatch.Builder.  
  This should leave all existing usages of LNP intact, but doubles the amount of code in LNP.
2. LibGui would need a custom shader program that supports tiling - and I will not be the one writing that.

---

> Type variables should not be upper camel case

I believe that single letter generic types lack descriptiveness.  
Hence I named it what it is, a generic Type intended for Textures.  
If you prefer I can use uppercase with underscores.

---

> I believe removing the UV coordinates will not allow drawing partial side textures like this

True, the above mentioned option 1 could resolve that.

2023-02-09 15:24 UTC, Juuxel commented
The partial side textures are definitely a feature that needs to be kept, otherwise the tiles will be stretched (so there's no point in tiling to begin with) or will bleed over past the corners.

---

As for the generic naming, `SCREAMING_SNAKE_CASE` is what the JDK uses (see stream code for example), and the `Type` suffix is also useless. So `T`, `TEX` and `TEXTURE` should all be fine.

2023-02-09 16:07 UTC, BlazingTwist commented
Any comment on which of the 3 options you prefer?

2023-02-09 18:24 UTC, Juuxel commented
I'm actually looking into the shader approach - a bit more work on the LibGui side but really simple on LNP's and doesn't require any breaking (or otherwise major) changes. Seems to also be more performant than the current approach just like yours.

On the LNP side it's just the new `drawTiled` method in texture renderers from the original approach in this PR.

I'll open PRs to both projects to show my changes if you want to have a look.

2023-03-17 18:07 UTC, Juuxel commented
Superseded by #3.

2023-03-17 18:07 UTC, closed without merging